repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run python -m black
    language: system
    types_or: [python, jupyter]
    args: [--config=./pyproject.toml]
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: poetry run python -m isort --resolve-all-configs
    language: system
    types: [python]
# poetry lock --check 在部分 Poetry 版本中不存在，如需检查请手动运行 poetry lock --check
# - repo: local
#   hooks:
#   - id: poetry lock
#     name: poetry lock check
#     entry: poetry lock --check
#     pass_filenames: false
#     language: system
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: poetry run python -m mypy
    pass_filenames: false
    language: system
    types: [python]
    args: ["--config-file=pyproject.toml", "."]
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: poetry run python -m pylint
    language: system
    types: [python]
